from dataclasses import dataclass

@dataclass
class TrainConfig:
    # --- Paths ---
    # Directory where setup.py downloaded the files
    model_dir: str = "./pretrained_models"
    
    # Path to your metadata CSV (Format: ID|RawText|NormText)
    csv_path: str = "./MyTTSDataset/metadata.csv"
    metadata_path: str = "./metadata.json"
    
    # Directory containing WAV files
    wav_dir: str = "./MyTTSDataset/wavs"
    #wav_dir: str = "./FileBasedDataset"
    
    preprocessed_dir = "./MyTTSDataset/preprocess"
    #preprocessed_dir = "./FileBasedDataset/preprocess"
    
    # Output directory for the finetuned model
    output_dir: str = "./chatterbox_output"
    resume_from_checkpoint: str = "./chatterbox_output/checkpoint-14000"
    
    is_inference = False
    inference_prompt_path: str = "./speaker_reference/chinh.wav"
    inference_test_text: str = "Xin chào, đây là bản thử giọng tiếng Việt sau khi fine-tune."


    # Dataset format is fixed to LJSpeech in this fork.
    ljspeech = True
    json_format = False
    preprocess = False # If you've already done preprocessing once, set it to false.
    
    vietnamese_only: bool = True

    # --- Runtime ---
    force_single_gpu: bool = True
    single_gpu_id: int = 0

    # --- Vocabulary ---
    # The size of the NEW vocabulary (from tokenizer.json)
    # Ensure this matches the JSON file generated by your tokenizer script.
    new_vocab_size: int = 206

    # --- Hyperparameters ---
    batch_size: int = 8        # Adjust based on VRAM (2, 4, 8)
    grad_accum: int = 2        # Effective Batch Size = Batch * Accum
    learning_rate: float = 1e-5 # T3 is sensitive, keep low
    num_epochs: int = 500
    
    save_steps: int = 5000
    save_total_limit: int = 2
    dataloader_num_workers: int = 8

    # --- Constraints ---
    # Must match tokenizer.json ids for [START] and [STOP].
    start_text_token = 205
    stop_text_token = 206
    max_text_len: int = 256
    max_speech_len: int = 650   # Truncates very long audio
    prompt_duration: float = 3.0 # Duration for the reference prompt (seconds)

    # --- Text normalization (Vietnamese) ---
    use_phoneme: bool = True
    use_g2p: bool = True
    normalize_numbers: bool = True
    normalize_abbrev: bool = True
    drop_unk_samples: bool = True

    # --- Training stability ---
    seed: int = 42
    warmup_ratio: float = 0.03
    max_grad_norm: float = 1.0
